= SBuild Adept Plugin

This SBuild plugin provides a Plugin to build SBuild Plugins.

== Installation

There is currently no release of this plugin. You need to build it by yourself.

== Building from Source

You need a recent version of SBuild.

----
git clone https://github.com/SBuild-org/sbuild-sbuild-plugin.git
cd sbuild-sbuild-plugin/org.sbuild.plugins.sbuildplugin
sbuild all
----

You will find the built jar in the directory `org.sbuild.plugins.sbuildplugin/target`.

== Configuration

All configurable properties are documented via ScalaDoc. See file SBuildPlugin.

== Usage Example

To build an imaginary `ExamplePlugin` in package `org.sbuild.plugins.example` in version `0.1.0` you can use the following SBuild buildfile. Scala source files are assumed to be in `src/main/scala` directory.

[source,scala]
----
import de.tototec.sbuild._

@version("0.7.0")
@classpath("org.sbuild.plugins.sbuildplugin.jar")
class SBuild(implicit _project: Project) {

  Plugin[org.sbuild.plugins.sbuildplugin.SBuildPlugin] configure { c =>
    // the version of SBuild this plugin is compatible to
    c.sbuildVersion = "0.7.0"
    
    // the plugin API
    c.pluginClass = "org.sbuild.plugins.example.Example"
    // the version of this plugin
    c.pluginVersion = "0.1.0"
    // the plugin factory class, which extends trait de.tototec.sbuild.Plugin
    c.pluginFactoryClass = "org.sbuild.plugins.example.ExamplePlugin"
  }

}
----

That's all to compile and package a plugin which has no additional dependencies.

----
bash$ sbuild -l
/tmp/exampleproject/target/org.sbuild.plugins.example-0.1.0.jar 
clean 
compile 
jar
----

To build the plugin use the `jar` target, which is an alias to the output jar (`target/org.sbuild.plugins.example-0.1.0.jar`).

== Future development

The SBuild plugin ecosystem just was born. If there are in the near future stable plugin for tasks like compiling, packaging, testing, etc, this plugin will start to use these instead of defining all these task on its own.
