= SBuild Adept Plugin

This SBuild plugin provides a Plugin to build http://sbuild.tototec.de[SBuild] Plugins.

== Binary releases

The SBuild Plugin Plugin is available from Maven Central Repository under groupId `org.sbuild` and teh artifactId `org.sbuild.plugins.sbuildplugin`.

To use it in SBuild 0.7.1 or above, simply add it to the project classpath.

[source,scala]
----
@classpath("mvn:org.sbuild:org.sbuild.plugin.sbuildplugin:0.2.0")
----

== Configuration

All configurable properties are documented via ScalaDoc in the configuration class link:org.sbuild.plugins.sbuildplugin/src/main/scala/org/sbuild/plugins/sbuildplugin/SBuildPlugin.scala[`SBuildPlugin`].

== Usage Example

To build an imaginary `ExamplePlugin` in package `org.sbuild.plugins.example` in version `0.1.0` you can use the following SBuild buildfile. Scala source files are assumed to be in `src/main/scala` directory.

[source,scala]
----
import de.tototec.sbuild._

@version("0.7.1")
@classpath("mvn:org.sbuild:org.sbuild.plugins.sbuildplugin:0.1.0.9000")
class SBuild(implicit _project: Project) {

  Plugin[org.sbuild.plugins.sbuildplugin.SBuildPlugin] configure { _.copy(
    // the version of SBuild this plugin is compatible to
    sbuildVersion = "0.7.1",
    // the plugin API
    c.pluginClass = "org.sbuild.plugins.example.Example",
    // the version of this plugin
    c.pluginVersion = "0.1.0",
    // the plugin factory class, which extends trait de.tototec.sbuild.Plugin
    c.pluginFactoryClass = "org.sbuild.plugins.example.ExamplePlugin",
  )}

}
----

That's all to compile and package a plugin which has no additional dependencies.

----
bash$ sbuild -l
/tmp/exampleproject/target/org.sbuild.plugins.example-0.1.0.jar 
clean 
compile 
jar
----

To build the plugin use the `jar` target, which is an alias to the output jar (`target/org.sbuild.plugins.example-0.1.0.jar`).

== Building from Source

You need a recent version of SBuild.

----
git clone https://github.com/SBuild-org/sbuild-sbuild-plugin.git
cd sbuild-sbuild-plugin/org.sbuild.plugins.sbuildplugin
sbuild all
----

You will find the built jar in the directory `org.sbuild.plugins.sbuildplugin/target`.


== Future development

The SBuild plugin ecosystem just was born. If there are in the near future stable plugin for tasks like compiling, packaging, testing, etc, this plugin will start to use these instead of defining all these task on its own.


== Changelog

=== SBuild Plugin Plugin 0.2.0 - 2013-12-21

* This version requires at least SBuild 0.7.1!
* Changed to immutable config class `SBuildPlugin`

=== SBuild Plugin Plugin 0.1.0 - 2013-12-18

* Initial Release, compatible to SBuild 0.7.0
